import type { ITicket } from '../types/ticket'

export const ticketsData: ITicket[] = [
  {
    id: 1,
    title: 'Login button not responding',
    description:
      'Users report the login button on the homepage does nothing when clicked on Safari.',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-08-20',
    updatedAt: '2025-08-21',
    organization: 'Paymob',
    notes: 'Reproduced on Safari 16.5. Possibly related to click handler being blocked by overlay.',
  },
  {
    id: 2,
    title: 'Typo in FAQ section',
    description: 'Misspelling of the word "organization" on the FAQ page.',
    priority: 'low',
    status: 'closed',
    createdAt: '2025-08-18',
    updatedAt: '2025-08-19',
    organization: 'Fawry',
    notes: 'Fixed in CMS. Verified by content team.',
  },
  {
    id: 3,
    title: 'Slow dashboard load',
    description:
      'Dashboard takes more than 8 seconds to load for some users in EU region.',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-08-22',
    updatedAt: '2025-08-23',
    organization: 'Paymob',
    notes: 'Added logging around DB queries. Suspect N+1 issue in reports widget.',
  },
  {
    id: 4,
    title: 'Notification badge count incorrect',
    description:
      'Badge shows unread notifications even after viewing all items.',
    priority: 'low',
    status: 'pending',
    createdAt: '2025-08-24',
    updatedAt: '2025-08-24',
    organization: 'Fawry',
    notes: 'Likely caching issue. Invalidate on mark-as-read not firing.',
  },
  {
    id: 5,
    title: 'Export to CSV fails',
    description:
      'Clicking export triggers an error for large datasets (>10k rows).',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-08-25',
    updatedAt: '2025-08-26',
    organization: 'Paymob',
    notes: 'Memory spike observed. Consider streaming export or pagination.',
  },
  {
    id: 6,
    title: 'Avatar upload rotates image',
    description: 'Uploaded profile photos appear rotated 90 degrees on mobile.',
    priority: 'medium',
    status: 'closed',
    createdAt: '2025-08-17',
    updatedAt: '2025-08-20',
    organization: 'Fawry',
    notes: 'Handled EXIF orientation during upload. Deployed fix on 20 Aug.',
  },
  {
    id: 7,
    title: '2FA code email delayed',
    description:
      'Email with the 2FA code arrives after 5-10 minutes for some domains.',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-08-27',
    updatedAt: '2025-08-27',
    organization: 'Paymob',
    notes: 'Mail provider rate limiting suspected. Monitoring added.',
  },
  {
    id: 8,
    title: 'Billing page 500 error',
    description:
      'Server returns 500 when opening Billing page for accounts with no payment method.',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-08-28',
    updatedAt: '2025-08-28',
    organization: 'Fawry',
    notes: 'Null-check missing for payment method. Patch in review.',
  },
  {
    id: 9,
    title: 'Search results pagination off by one',
    description:
      'Page 2 repeats the last items from page 1 and misses the last page.',
    priority: 'low',
    status: 'closed',
    createdAt: '2025-08-14',
    updatedAt: '2025-08-16',
    organization: 'Paymob',
    notes: 'Adjusted offset calculation. Added unit test coverage.',
  },
  {
    id: 10,
    title: 'Dark mode contrast issue',
    description:
      'Text in disabled inputs has insufficient contrast in dark mode.',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-08-29',
    updatedAt: '2025-08-30',
    organization: 'Fawry',
    notes: 'Updated token values to meet WCAG AA contrast ratios.',
  },
]
